package consts

const ( 
	AI_ROUTING_KEY = "AI"
	AGENT_REQUEST_ROUTING_KEY = AI_ROUTING_KEY + "." +  "AGENT.REQUEST"
)

const (
	PLAYER_ROUTING_KEY = "PLAYER"
	PLAYER_RESPONSE_ROUTING_KEY = PLAYER_ROUTING_KEY + "." + "RESPONSE."
)

const GAME_EXCHANGE_NAME = "GAME_EXCHANGE"
