package consts
//接收者 Agent
const (
	AGENT_RECEIVE_FROM_PLAYER_ROUTING_KEY string  = "AGENT.FROM.PLAYER.REQUEST"
	AGENT_RECEIVE_FROM_CONNECT_ROUTING_KEY string = "AGENT.FROM.CONNECT.REQUEST"
)
//接收者 Player
const (
	PLAYER_RECEIVE_FROM_AI_ROUTING_KEY string = "PLAYER.FROM.AI."
)
//接收者 Game
const (
	GAME_RECEIVE_FROM_CONNECTOR_ROUTING_KEY string = "GAME.FROM.CONNECTOR."
)
//接收者 Connector
const (
	CONNECTOR_RECEIVE_FROM_GAME_ROUTING_KEY string  = "CONNECTOR.FROM.GAME."
	CONNECTOR_RECEIVE_FROM_AGENT_ROUTING_KEY string = "CONNECTOR.FROM.AGENT"
)

const GAME_EXCHANGE_NAME string = "GAME_EXCHANGE"
