package consts
//接收者 Agent
// const (
// 	AGENT_RECEIVE_FROM_PLAYER_ROUTING_KEY string  = "AGENT.FROM.PLAYER.REQUEST"
// 	AGENT_RECEIVE_FROM_CONNECT_ROUTING_KEY string = "AGENT.FROM.CONNECT.REQUEST"
// )
//接收者 Player
// const (
// 	PLAYER_RECEIVE_FROM_AI_ROUTING_KEY string = "PLAYER.FROM.AI."
// )
// //接收者 Game
// const (
// 	GAME_RECEIVE_FROM_CONNECTOR_ROUTING_KEY string = "GAME.FROM.CONNECTOR."
// )
// //接收者 Connector
// const (
// 	CONNECTOR_RECEIVE_FROM_GAME_ROUTING_KEY string  = "CONNECTOR.FROM.GAME."
// 	CONNECTOR_RECEIVE_FROM_AGENT_ROUTING_KEY string = "CONNECTOR.FROM.AGENT"
// )

var ROUTING = routing{
	AGENT: agentRouting{
		FROM_GAME: "AGENT.FROM.GAME",
		FROM_CONNECTOR: "AGENT.FROM.CONNECTOR",
	},
	GAME: gameRouting{
		FROM_AGENT: "GAME.FROM.AGENT",
		FROM_CONNECTOR: "GAME.FROM.CONNECTOR",
	},
	CONNECTOR: connectRouting{
		FROM_AGENT: "CONNECTOR.FROM.AGENT",
		FROM_GAME: "CONNECT.FROM.GAME",
	},
}

type routing struct {
	AGENT agentRouting
	GAME gameRouting
	CONNECTOR connectRouting
}

type agentRouting struct {
	FROM_GAME string
	FROM_CONNECTOR string
} 


type gameRouting struct {
	FROM_CONNECTOR string
	FROM_AGENT string
}

type connectRouting struct {
	FROM_GAME string
	FROM_AGENT string
}

// const (
// 	AGENT_REQUEST_FROM_CONNECTOR_ROUTING_KEY string = "Agent.Request.From.Connector."
// 	AGENT_REQUEST_FROM_GAME_KEY string  = "Agent.Request.From.Game."
// 	AGENT_RESPONSE_TO_CONNECTOR_ROUTING_KEY string = "AGENT.TO.CONNECTOR."
// 	AGENT_RESPONSE_TO_GAME_ROUTING_KEY string = "AGENT.TO.GAME."
// )

// const (
// 	CONNECTOR_REQUEST_FROM_AGENT_ROUTING_KEY string = "CONNECTOR.TO.AGENT."
// 	CONNECTOR_REQUEST_FROM_GAME_KEY string  = "CONNECTOR.TO.GAME."
// 	CONNECTOR_RESPONSE_TO_AGENT_ROUTING_KEY string = "CONNECTOR.TO.AGENT."
// 	CONNECTOR_RESPONSE_TO_GAME_ROUTING_KEY string = "CONNECTOR.TO.GAME."
// )

// const (
// 	GAME_REQUEST_FROM_AGENT_ROUTING_KEY string = "GAME.TO.AGENT."
// 	GAME_REQUEST_FROM_CONNECTOR_ROUTING_KEY string = "GAME.TO.CONNECTOR."
// 	GAME_RESPONSE_TO_AGENT_ROUTING_KEY string = "GAME.TO.AGENT."
// 	GAME_RESPONSE_TO_CONNECTOR_ROUTING_KEY string = "GAME.TO.CONNECTOR."
// )

const GAME_EXCHANGE_NAME string = "GAME_EXCHANGE"
